global:
  scrape_interval: 15s
  evaluation_interval: 15s
  query_log_file: /prometheus/query.log


scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
- job_name: 'kong' 
  metrics_path: /metrics
  honor_labels: false
  scrape_interval: "5s"
  honor_timestamps: true
  sample_limit: 0
  static_configs:
    - targets: ['kong-gateway:8001']